TOPDIR = $(realpath $(CURDIR)/..)

OBJS = audio.o c2p1x1_8_c5_bm.o display.gfx.o hardware.o \
       iff.o inflate.o input.o rwops.o rwops-file.o rwops-memory.o zip.o

libsystem.a: $(OBJS)

include $(TOPDIR)/Makefile.common
