TOPDIR := $(realpath ../..)
CLEAN-FILES := data/background.c data/spiders.c 

PNG2C.background := --bitmap background_bmp,320x256x4 --palette back_pal,16
PNG2C.spiders := --sprite spiders_sprite,16,8
SOURCES := spring.c

include $(TOPDIR)/build/effect.mk


