TOPDIR := $(realpath ../..)

CLEAN-FILES := data/dragon-bg.c data/speccy.c

PNG2C.dragon-bg := --bitmap background,320x256x4 --palette background,16
PNG2C.speccy := --palette speccy,16

include $(TOPDIR)/build/effect.mk
