TOPDIR := $(realpath ../..)

DATA_GEN := data/twister-gradient.ilbm \
	    data/twister-left.ilbm \
	    data/twister-right.ilbm \
	    data/twister.ilbm
DATA := data/twister-texture.png

include $(TOPDIR)/build.effect.mk
