TOPDIR := $(realpath ../..)

SOURCES := \
	ClipLine2D.c \
	ClipPolygon2D.c \
	ClipWin.c \
	LoadIdentity2D.c \
	PointsInsideBox.c \
	Rotate2D.c \
	Scale2D.c \
	Transform2D.c \
	Translate2D.c

include $(TOPDIR)/build/lib.mk
