TOPDIR := $(realpath ../..)

CLEAN-FILES := data/shapes-pal.c data/night.c data/boxes.c

LIBS := lib2d

PNG2C.shapes-pal := --palette shapes_pal,16
CONV2D.night := --name shape

include $(TOPDIR)/build.effect.mk
