#!/bin/bash
# This file must be used with "source activate"

[ -e /etc/debian_version ] || \
  echo "Warning: Unsupported Linux distribution!"

function demoscene_config {
  MODEL=A500
  PREFIX=/opt/amiga

  local opt
  while getopts "m:p:" opt $@; do
    case ${opt} in
      m)
        case ${OPTARG} in
          A500|A1200)
            MODEL="${OPTARG}"
            ;;
          *)
            echo "Unknown Amiga model: ${OPTARG}!"
            return 1
            ;;
        esac
        ;;
      p)
        PREFIX="${OPTARG}"
        ;;
      \?)
        return 1
        ;;
    esac
  done

  export MODEL
  return 0
}

function demoscene_check {
  local PACKAGES
  PACKAGES=(git-lfs optipng gcc g++ make golang
    python3 python3-pip python3-venv python3-dev socat tmux)

  local package
  for package in "${PACKAGES[@]}"; do
    if ! dpkg -l ${package} 1>/dev/null 2>/dev/null; then
      echo "Package ${package} is not installed!"
      echo "Run: sudo apt-get install ${package}"
      return 1
    fi
  done

  local EXECUTABLES
  EXECUTABLES=(m68k-amigaos-gcc m68k-amigaos-ld m68k-amigaos-as m68k-amigaos-gdb
    fs-uae vasm lzsa salvador Shrinkler)

  local executable
  for executable in "${EXECUTABLES[@]}"; do
    if ! [ -x ${PREFIX}/bin/${executable} ]; then \
      echo "No ${executable} found in ${PREFIX}!"
      echo "Please install latest demoscene-toolchain deb package from:"
      echo "https://github.com/cahirwpz/demoscene-toolchain/releases/"
      return 1
    fi
  done

  return 0
}

function demoscene_activate {
  export PATH=${PREFIX}/bin:${PATH}

  python3 -m venv .venv
  source .venv/bin/activate
  python3 -m pip -q install -U -r requirements.txt
}

if demoscene_config $@; then
  if demoscene_check; then
    demoscene_activate

    echo "Demoscene build environment in $(pwd) configured for ${MODEL}!"
    export DEMOSCENE_ROOT=$(pwd)
  fi
else
  echo ""
  echo "Usage: source activate -m MODEL -p PREFIX"
  echo ""
  echo "Where:"
  echo " MODEL is A500 or A1200 (default: A500)"
  echo " PREFIX points to toolchain installation (default: /opt/amiga)"
fi
