TOPDIR := $(realpath ../..)

SOURCES := rotator.c mainloop.asm
CLEAN-FILES := data/stained-glass.c

PNG2C.stained-glass := --pixmap texture,128x128x8 --palette texture_pal,16

include $(TOPDIR)/build/effect.mk
