TOPDIR := $(realpath ../..)

SOURCES := rotator.c mainloop.asm
CLEAN-FILES := data/rork-128.c

PNG2C.rork-128 := --pixmap texture,128x128x8,+onlydata --palette texture,16

include $(TOPDIR)/build/effect.mk
