TOPDIR := $(realpath ../..)

SOURCES := \
	gen/ctype.c \
	gen/divsi3.s \
	gen/modsi3.s \
	gen/mulsi3.s \
	gen/udivsi3.s \
	gen/umodsi3.s \
	stdlib/random.c \
	stdio/kvprintf.c \
	stdio/snprintf.c \
	string/bzero.s \
	string/memcpy.s \
	string/memset.s \
	string/strcmp.s \
	string/strcpy.s \
	string/strlen.s

include $(TOPDIR)/build/lib.mk
