TOPDIR := $(realpath ../..)

SOURCES := \
	__divsi3.s \
	__modsi3.s \
	__mulsi3.s \
	__udivsi3.s \
	__umodsi3.s \
	bzero.s \
	kvprintf.c \
	memcpy.s \
	memset.s \
	snprintf.c \
	strcmp.s \
	strcpy.s \
	strlen.s

include $(TOPDIR)/build/lib.mk
