TOPDIR = $(realpath $(CURDIR)/..)

OBJS = common.o offset.o raycast.o render.o render-opt.o scaling.o \
       scaling-opt.o sine.o tunnel.o twirl.o

libuvmap.a: $(OBJS)

include $(TOPDIR)/Makefile.common
