TOPDIR = $(realpath $(CURDIR)/..)

OBJS = common.o offset.o raycast.o render.o scaling.o sine.o tunnel.o twirl.o \
       render-opt-1.o render-opt-2.o scaling-opt-1.o scaling-opt-2.o

libuvmap.a: $(OBJS)

include $(TOPDIR)/Makefile.common
