TOPDIR := $(realpath ../..)

CLEAN-FILES := data/blurred3d-pal.c data/szescian.c

LIBS := lib3d

PNG2C.blurred3d-pal := --pixmap gradient,16x33x12
OBJ2C.szescian := --scale 93.0

include $(TOPDIR)/build/effect.mk
