TOPDIR := $(realpath ../..)

DATA_GEN := data/ball.3d data/pilka.3d
CLEAN-FILES := data/flatshade-pal.c

LIBS := lib3d

PNG2C.flatshade-pal := --palette flatshade_pal,16

include $(TOPDIR)/build.effect.mk
