TOPDIR := $(realpath ../..)

CLEAN-FILES := data/flatshade-pal.c data/ball.c data/pilka.c

LIBS := lib3d

PNG2C.flatshade-pal := --palette flatshade_pal,16
LWO2C.ball := --scale 110.0
LWO2C.pilka := --scale 65.0

include $(TOPDIR)/build/effect.mk
