TOPDIR := $(realpath ../..)

CLEAN-FILES := data/*.c

PNG2C.ground  := --bitmap ground,640x16x1
PNG2C.ground2 := --bitmap ground2,640x16x1

PNG2C.tree1 := --sprite tree1,256,2
PNG2C.tree2 := --sprite tree2,256,2
PNG2C.tree3 := --sprite tree3,256,2

# PNG2C.ghost := --sprite ghost,50,2
# PNG2C.moon := --sprite moon,32,2
PNG2C.moonghost := --sprite moonghost,82,2
PNG2C.moonbatghost1 := --sprite moonbatghost1,100,2
PNG2C.moonbatghost2 := --sprite moonbatghost2,100,2

include $(TOPDIR)/build/effect.mk
