TOPDIR := $(realpath ../..)

SOURCES := \
	AllFacesDoubleSided.c \
	Compose3D.c \
	DeleteObject3D.c \
	LoadIdentity3D.c \
	LoadReverseRotate3D.c \
	LoadRotate3D.c \
	NewObject3D.c \
	Scale3D.c \
	SortFaces.c \
	SortFacesMinZ.c \
	Transform3D.c \
	Translate3D.c \
	UpdateFaceVisibility.c \
	UpdateObjectTransformation.c \
	UpdateVertexVisibility.c

include $(TOPDIR)/build/lib.mk
