TOPDIR := $(realpath ../..)

CLEAN-FILES := data/toggle_0.c data/toggle_1.c data/koi8r.8x8.c

LIBS := libgui

PNG2C.toggle_0 := --bitmap toggle_0,16x16x1
PNG2C.toggle_1 := --bitmap toggle_1,16x16x1
PSF2C.koi8r.8x8 := --name font

include $(TOPDIR)/build.effect.mk
