TOPDIR := $(realpath ../..)

DATA :=	data/koi8r.8x8.font
DATA_GEN := data/koi8r.8x8.png \
	    data/koi8r.8x8.ilbm \
	    data/toggle_0.ilbm \
	    data/toggle_1.ilbm

LIBS := libgui

include $(TOPDIR)/build.effect.mk
