DATA := data/greet_ada.ilbm \
	data/greet_blacksun.ilbm \
	data/greet_dcs.ilbm \
	data/greet_dekadence.ilbm \
	data/greet_desire.ilbm \
	data/greet_dinx.ilbm \
	data/greet_elude.ilbm \
	data/greet_fd.ilbm \
	data/greet_floppy.ilbm \
	data/greet_lemon.ilbm \
	data/greet_loonies.ilbm \
	data/greet_moods.ilbm \
	data/greet_nah.ilbm \
	data/greet_rno.ilbm \
	data/greet_skarla.ilbm \
	data/greet_speccy.ilbm \
	data/greet_tulou.ilbm \
	data/greet_wanted.ilbm \
	data/greet_ycrew.ilbm \
	data/neons.ilbm

all: neons.exe

include ../build.mk
