TOPDIR := $(realpath ../..)

SOURCES := \
	BitmapAddSaturated.c \
	BitmapCopy.c \
	BitmapCopyArea.c \
	BitmapCopyFast.c \
	BitmapCopyMasked.c \
	BitmapDecSaturated.c \
	BitmapIncSaturated.c \
	BitmapMakeMask.c \
	BitmapSetArea.c \
	BlitterCopy.c \
	BlitterCopyArea.c \
	BlitterCopyFast.c \
	BlitterCopyMasked.c \
	BlitterFillArea.c \
	BlitterLine.c \
	BlitterSetArea.c \
	BlitterSetMaskArea.c \
	WordMask.c \

include $(TOPDIR)/build/lib.mk
