SOURCES_C := \
	circle.c \
	color.c \
	coplist.c \
	gfx.c \
	ilbm.c \
	line.c \
	pixmap.c \
	png.c \
	sprite.c

SOURCES_ASM := \
	c2p_1x1_4.s

all: libgfx.a

include ../../build.mk

libgfx.a: $(OBJECTS)
