TOPDIR := $(realpath ../..)

DATA_GEN := data/01_cahir.ilbm \
	    data/02_slayer.ilbm \
	    data/03_jazzcat.ilbm \
	    data/04_dkl.ilbm \
	    data/05_dance1.ilbm \
	    data/06_dance2.ilbm \
	    data/07_dance3.ilbm \
	    data/08_dance4.ilbm \
	    data/credits_logo.ilbm \
	    data/discoball.ilbm \
	    data/floor.ilbm \
	    data/insert_coin.ilbm \
	    data/txt_cahir.ilbm \
	    data/txt_codi.ilbm \
	    data/txt_dkl.ilbm \
	    data/txt_jazz.ilbm \
	    data/txt_slay.ilbm

include $(TOPDIR)/build.effect.mk
