TOPDIR := $(realpath ../..)

CLEAN-FILES := \
	data/01_cahir.c \
	data/02_slayer.c \
	data/03_jazzcat.c \
	data/04_dkl.c \
	data/05_dance1.c \
	data/06_dance2.c \
	data/07_dance3.c \
	data/08_dance4.c \
	data/credits_logo.c \
	data/discoball.c \
	data/floor.c \
	data/txt_cahir.c \
	data/txt_codi.c \
	data/txt_dkl.c \
	data/txt_jazz.c \
	data/txt_slay.c

PNG2C.credits_logo := --bitmap logo,256x64x4 --palette logo,16
PNG2C.discoball := --bitmap disco,64x64x4 --palette disco,15
PNG2C.floor := --bitmap floor,288x112x3 --palette floor,8
PNG2C.01_cahir := --bitmap cahir,160x112x3 --palette dance,8
PNG2C.02_slayer := --bitmap slayer,160x112x3
PNG2C.03_jazzcat := --bitmap jazzcat,160x112x3
PNG2C.04_dkl := --bitmap dkl,160x112x3
PNG2C.05_dance1 := --bitmap dance1,160x112x3
PNG2C.06_dance2 := --bitmap dance2,160x112x3
PNG2C.07_dance3 := --bitmap dance3,160x112x3
PNG2C.08_dance4 := --bitmap dance4,160x112x3
PNG2C.txt_cahir := --bitmap txt_cahir,128x64x4 --palette member,15
PNG2C.txt_codi := --bitmap txt_codi,160x64x4
PNG2C.txt_dkl := --bitmap txt_dkl,192x64x4
PNG2C.txt_jazz := --bitmap txt_jazz,176x64x4
PNG2C.txt_slay := --bitmap txt_slay,144x64x4

include $(TOPDIR)/build/effect.mk
