TOPDIR := $(realpath ../..)

CLEAN-FILES := data/text-scroll-font.c
DATA := data/text-scroll.txt

PNG2C.text-scroll-font := --bitmap font,768x8x1 --palette font_pal,2

include $(TOPDIR)/build.effect.mk
