CPPFLAGS = -I../../include -I../
LIBS += libsys

include ../../Makefile.common

LIBFILES = $(foreach lib,$(LIBS),../../$(lib)/$(lib).a)

define emit_lib_rule
$(1):
	@echo "MAKE $(notdir $(1))"
	make -C $(dir $(1))
endef

$(foreach lib,$(LIBFILES),$(eval $(call emit_lib_rule,$(lib))))

%.exe: ../../crt0.o %.o ../startup.o $(LIBFILES)
	@echo "LINK $@"
	$(CC) $(LDFLAGS) -o $@ $^ $(LDLIBS)

.PHONY: $(LIBFILES)
