DATA := data/16_01_cahir.iff \
	data/16_02_slayer.iff \
	data/16_03_jazzcat.iff \
	data/16_04_dkl.iff \
	data/16_05_dance1.iff \
	data/16_06_dance2.iff \
	data/16_07_dance3.iff \
	data/16_08_dance4.iff \
	data/16_ball.bin \
	data/16_ball_texture.png \
	data/16_ball_texture.tga \
	data/16_credits_logo.iff \
	data/16_discoball.iff \
	data/16_floor.iff \
	data/16_insert_coin.iff \
	data/16_txt_cahir.iff \
	data/16_txt_codi.iff \
	data/16_txt_dkl.iff \
	data/16_txt_jazz.iff \
	data/16_txt_slay.iff

all: credits.exe

include ../build.mk
