DATA := data/01_cahir.iff \
	data/02_slayer.iff \
	data/03_jazzcat.iff \
	data/04_dkl.iff \
	data/05_dance1.iff \
	data/06_dance2.iff \
	data/07_dance3.iff \
	data/08_dance4.iff \
	data/credits_logo.iff \
	data/discoball.iff \
	data/floor.iff \
	data/insert_coin.iff \
	data/txt_cahir.iff \
	data/txt_codi.iff \
	data/txt_dkl.iff \
	data/txt_jazz.iff \
	data/txt_slay.iff

all: credits.exe

include ../build.mk
