SOURCES_ASM := \
	__divsi3.s \
	__modsi3.s \
	__mulsi3.s \
	__udivsi3.s \
	__umodsi3.s \
	bzero.s \
	memcpy.s \
	memset.s \
	strcmp.s \
	strcpy.s \
	strlen.s

SOURCES_C := \
	kvprintf.c \
	snprintf.c

all: libc.a

include ../../build.mk

libc.a:
