TOPDIR := $(realpath ../..)

SOURCES := \
	blitter.c \
	blt-add-sat.c \
	blt-copy-area.c \
	blt-copy-fast.c \
	blt-copy-mask.c \
	blt-copy.c \
	blt-dec-sat.c \
	blt-fill-area.c \
	blt-inc-sat.c \
	blt-line.c \
	blt-make-mask.c \
	blt-set-area.c \
	blt-set-mask-area.c

include $(TOPDIR)/build.lib.mk
