TOPDIR := $(realpath ../..)

CLEAN-FILES := data/wireframe-pal.c data/pilka.c

LIBS := lib3d

PNG2C.wireframe-pal := --palette wireframe_pal,16
LWO2C.pilka := --scale 65.0 

include $(TOPDIR)/build.effect.mk
