TOPDIR := $(realpath ../..)

CLEAN-FILES := data/wireframe-pal.c data/pilka.c data/codi.c

LIBS := lib3d

PNG2C.wireframe-pal := --palette wireframe,16
OBJ2C.pilka := --scale 65.0 

include $(TOPDIR)/build/effect.mk
