TOPDIR := $(realpath ../..)

CLEAN-FILES := data/thunders.c data/thunders-floor.c

PNG2C.thunders := --sprite thunder,128,20,+array --palette thunder,4
PNG2C.thunders-floor := --pixmap texture,8x8x12

include $(TOPDIR)/build/effect.mk
