TOPDIR := $(realpath ../..)

DATA := data/thunders-floor.png
CLEAN-FILES := data/thunders.c

PNG2C.thunders := --sprite thunder,128,20,+array --palette thunder_pal,4

include $(TOPDIR)/build.effect.mk
