TOPDIR := $(realpath ../..)

CLEAN-FILES := data/flares32.c data/pilka.c data/potato.c

LIBS := lib3d

PNG2C.flares32 := --bitmap bobs,512x32x3,+interleaved --palette bobs,8
OBJ2C.pilka := --scale 50.0

include $(TOPDIR)/build/effect.mk
