TOPDIR := $(realpath ../..)

CLEAN-FILES := data/flares32.c
DATA_GEN := data/pilka.3d

LIBS := lib3d

PNG2C.flares32 := --bitmap bobs,512x32x3,+interleaved --palette bobs_pal,8

include $(TOPDIR)/build.effect.mk
