#!/bin/sh

trap quit SIGINT

function quit() {
  kill $SOCAT
  kill $FSUAE
}

cat >s/startup-sequence <<EOF
$@
ExitUAE
EOF

# With such settings I can interact with ROMWACK :-)
socat PTY,link=/tmp/vser,raw,echo=0 STDOUT,raw,echo=0 &
SOCAT=$!
fs-uae >/dev/null &
FSUAE=$!
wait $FSUAE
kill -HUP $SOCAT

rm s/startup-sequence
