#!/bin/sh

trap quit SIGINT

function quit() {
  kill -INT $SER
  kill -INT $PAR
  kill $FSUAE
}

cat >s/startup-sequence <<EOF
$@
ExitUAE
EOF

# With such settings I can interact with ROMWACK :-)
socat PTY,link=/tmp/vser,raw,echo=0 STDOUT,raw,echo=0 &
SER=$!
socat -u PTY,link=/tmp/vpar,raw,echo=0 STDERR,raw,echo=0 &
PAR=$!
fs-uae >/dev/null &
FSUAE=$!
wait $FSUAE
kill -INT $SER
kill -INT $PAR

rm s/startup-sequence
