DATA := data/highway-car-left-2.ilbm \
	data/highway-car-right-2.ilbm \
	data/highway-city-bottom-2.ilbm \
	data/highway-city-top-2.ilbm \
	data/highway-lane.ilbm \
	data/highway-sprite.ilbm

all: build-data highway.exe

include ../build.mk
