TOPDIR = $(realpath $(CURDIR)/..)

OBJS = exception.o fastmath.o hashmap.o fp16.o node.o list.o math.o \
       memory.o queue.o stack.o table.o

libstd.a: $(OBJS)

include $(TOPDIR)/Makefile.common

# vim: sw=8 ts=8
