TOPDIR := $(realpath ../..)

CLEAN-FILES := data/ghostown-logo.c data/stardust-?.c

PNG2C.ghostown-logo := --bitmap logo,160x128x2 --palette logo,4
PNG2C.stardust-1 := --bitmap stardust_1,448x192x2 --palette background,4
PNG2C.stardust-2 := --bitmap stardust_2,448x192x2
PNG2C.stardust-3 := --bitmap stardust_3,448x192x2
PNG2C.stardust-4 := --bitmap stardust_4,448x192x2
PNG2C.stardust-5 := --bitmap stardust_5,448x192x2
PNG2C.stardust-6 := --bitmap stardust_6,448x192x2

include $(TOPDIR)/build/effect.mk
