TOPDIR = $(realpath $(CURDIR)/..)

OBJS = channel.o convolution2d.o directionalblur.o plasma.o perlin.o \
			 perlinplasma.o procedural.o txtgen.o

libtxtgen.a: $(OBJS)

include $(TOPDIR)/Makefile.common
