TOPDIR := $(realpath ../..)

SOURCES := \
	area.c \
	bitmap.c \
	c2p_1x1_4.asm \
	circle.c \
	color.c \
	copper.c \
	dualpf.c \
	line.c \
	palette.c \
	pixmap.c \
	playfield.c \
	sprite.c

include $(TOPDIR)/build/lib.mk
