TOPDIR := $(realpath ../..)

SOURCES := \
	BitmapMakeDisplayable.c \
	BitmapSetPointers.c \
	BitmapSize.c \
	Circle.c \
	CircleEdge.c \
	ClipArea.c \
	ColorTab.c \
	ColorTransition.c \
	CopListActivate.c \
	CopListFinish.c \
	CopListReset.c \
	CopLoadColor.c \
	CopLoadColorArray.c \
	CopperStop.c \
	CopSetupBitplaneArea.c \
	CopSetupBitplaneFetch.c \
	CopSetupBitplanes.c \
	CopSetupDisplayWindow.c \
	CopSetupMode.c \
	CopSetupSprites.c \
	CopUpdateBitplanes.c \
	CpuEdge.c \
	CpuLine.c \
	DeleteBitmap.c \
	DeleteCopList.c \
	DeletePixmap.c \
	EndSprite.c \
	HsvToRgb.c \
	InitSharedBitmap.c \
	InsideArea.c \
	LoadColorArray.c \
	MakeSprite.c \
	NewBitmap.c \
	NewCopList.c \
	NewPixmap.c \
	NullSprData.c \
	PixmapScramble_4_1.c \
	PixmapScramble_4_2.c \
	ResetSprites.c \
	SetupBitplaneFetch.c \
	SetupDisplayWindow.c \
	SetupMode.c \
	SetupPlayfield.c \
	SpriteUpdatePos.c \
	c2p_1x1_4.asm

include $(TOPDIR)/build/lib.mk
