TOPDIR := $(realpath ../..)

SOURCES := \
	BitmapMakeDisplayable.c \
	BitmapSetPointers.c \
	BitmapSize.c \
	Circle.c \
	CircleEdge.c \
	ClipArea.c \
	ColorTab.c \
	ColorTransition.c \
	CopListActivate.c \
	CopLoadColor.c \
	CopLoadPal.c \
	CopSetupBitplaneArea.c \
	CopSetupBitplaneFetch.c \
	CopSetupBitplanes.c \
	CopSetupBitplanesUpsideDown.c \
	CopSetupDisplayWindow.c \
	CopSetupDualPlayfield.c \
	CopSetupManualSprites.c \
	CopSetupMode.c \
	CopSetupSprites.c \
	CopUpdateBitplanes.c \
	CpuEdge.c \
	CpuLine.c \
	DeleteBitmap.c \
	DeleteCopList.c \
	DeletePixmap.c \
	DeleteSprite.c \
	InitSharedBitmap.c \
	InsideArea.c \
	LoadPalette.c \
	NewBitmapCustom.c \
	NewCopList.c \
	NewPixmap.c \
	NewSprite.c \
	NullSprite.c \
	PixmapScramble_4_1.c \
	PixmapScramble_4_2.c \
	SetupPlayfield.c \
	UpdateSprite.c \
	c2p_1x1_4.asm

include $(TOPDIR)/build/lib.mk
