TOPDIR = $(realpath $(CURDIR)/..)

OBJS = blit.o raw.o colorfunc.o colors.o ellipse.o filter.o hsl.o layers.o line.o \
       matrix2d.o ms2d.o palette.o pixbuf.o png.o quantize.o rectangle.o \
       spline.o triangle.o

libgfx.a: $(OBJS)

include $(TOPDIR)/Makefile.common
