TOPDIR = $(realpath $(CURDIR)/..)

OBJS = blit.o colors.o ellipse.o hsl.o line.o matrix2d.o ms2d.o \
       palette.o pixbuf.o quantize.o spline.o triangle.o

libgfx.a: $(OBJS)

include $(TOPDIR)/Makefile.common
