TOPDIR := $(realpath ../..)

CLEAN-FILES := data/roller-bg.c data/magland16.c

PNG2C.roller-bg := --bitmap roller_bp,320x256x4,+displayable
PNG2C.magland16 := --palette texture_pal,16 --pixmap texture_bp,16x54x8

include $(TOPDIR)/build/effect.mk

