TOPDIR = $(realpath $(CURDIR)/..)

OBJS = array.o fastmath.o fp16.o node.o list.o math.o memory.o \
			 queue.o resource.o stack.o table.o

libstd.a: $(OBJS)

include $(TOPDIR)/Makefile.common

# vim: sw=8 ts=8
