TOPDIR = $(realpath $(CURDIR)/..)

OBJS = aaline.o blit.o colorfunc.o colors.o ellipse.o filter.o hsl.o layers.o \
       line.o matrix2d.o ms2d.o palette.o pixbuf.o png.o rectangle.o spline.o \
       triangle_cf.o triangle_i.o raw-1.o raw-2.o

libgfx.a: $(OBJS)

include $(TOPDIR)/Makefile.common
