TOPDIR := $(realpath ../..)

CLEAN-FILES := data/dragon-bg.c
DATA := data/texture-15.png data/ball.bin

PNG2C.dragon-bg := --bitmap background,320x256x4 --palette background_pal,16

include $(TOPDIR)/build.effect.mk
