name: Demoscene

on: [push, pull_request]

jobs:
  style:
    name: Python Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
      - name: Check Python code style
        run: bash style-python

  build:
    name: Build
    runs-on: ubuntu-latest
    container: cahirwpz/demoscene:latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: effects
          path: effects/*/*.adf
